DATA:
  depth_augm:
    clip: 0.005
    gaussian_kernel: 0
    sigma: 0.001
  input_normals: True
  intrinsics: realsense
  pc_augm:
    clip: 0.005
    occlusion_dropout_rate: 0.0
    occlusion_nclusters: 0
    sigma: 0.0
  raw_num_points: 20000
  use_farthest_point: false
  use_uniform_quaternions: false
  view_sphere:
    distance_range:
    - 1.0
    - 1.3
    elevation:
    - 340
    - 370